FORMAT: 1A

# Card Game API

Card Game API is a simple API allowing consumers to create and play simple card games.

## Cards Collection [/cards]

### List All Cards [GET]

Lists all cards.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "description": "Ace of Spades",
                "value": 1,
                "suite": "spades"
            },
            {
                "id": 2,
                "description": "Two of Spades",
                "value": 2,
                "suite": "spades"
            }
        ]

### Create a New Card [POST]

You may create your own card using this action. It takes a JSON
object containing a card.

+ Request (application/json)

        {
            "description": "Lord of Spades",
            "value": 100,
            "suite": "spades"
        }

+ Response 201 (application/json)

    + Headers

            Location: /cards/252

    + Body

            {
                "id": 252
                "description": "Lord of Spades",
                "value": 100,
                "suite": "spades"
            }